/*
ModuleId: 5F08DF74-3C4B-4DBD-AD35-26565239E157
Version: 1.0.0
ScriptId: 1FBA6358-7AC1-4B6F-82D6-48BBCBD5C99E
*/

IF	NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'REV_TEMP_DB_VERSION')
	AND
	NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'REV_SCRIPT_LOG')
		RAISERROR('Revo infrastructure init must be run first.', 20, 1)  WITH LOG;

--a bit more complex because of possible bootstrap phase
DECLARE @logId UNIQUEIDENTIFIER = NEWID();
DECLARE @timestamp DATETIME = GETDATE();
IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'REV_SCRIPT_LOG')
	INSERT INTO [dbo].[REV_SCRIPT_LOG] ([REV_SCL_ScriptLogId],[REV_SCL_ScriptId], [REV_SCL_ScriptVersion],[REV_SCL_ScriptType],[REV_SCL_ScriptName],[REV_SCL_DbVersionId],[REV_SCL_StartTimestamp],[REV_SCL_CompletionTimestamp])
	VALUES (@logId, '1FBA6358-7AC1-4B6F-82D6-48BBCBD5C99E', '1.0.0', 'STRUCTURE', '01_REV_CREATE', 'DCB948CF-C9DB-41C9-AE9C-C08E97BC87B2', @timestamp, null);
ELSE
	INSERT INTO [dbo].[REV_TEMP_SCRIPT_LOG] ([REV_SCL_ScriptLogId],[REV_SCL_ScriptId], [REV_SCL_ScriptVersion], [REV_SCL_ScriptType],[REV_SCL_ScriptName],[REV_SCL_DbVersionId],[REV_SCL_StartTimestamp],[REV_SCL_CompletionTimestamp])
	VALUES (@logId, '1FBA6358-7AC1-4B6F-82D6-48BBCBD5C99E', '1.0.0', 'STRUCTURE', '01_REV_CREATE', 'DCB948CF-C9DB-41C9-AE9C-C08E97BC87B2', @timestamp, null);
GO

/******
EVENT STORE
******/

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'RES_EVENT_STREAM')
CREATE TABLE [dbo].[RES_EVENT_STREAM] (
	[RES_EVS_EventStreamId] [UNIQUEIDENTIFIER] NOT NULL,
	[RES_EVS_Ordinal] [INT] IDENTITY(1,1) NOT NULL,
	[RES_EVS_Version] [INT] NOT NULL,
	[RES_EVS_MetadataJson] [NVARCHAR] (MAX),
	CONSTRAINT [RES_EVENT_STREAM_PK] PRIMARY KEY NONCLUSTERED ([RES_EVS_EventStreamId])
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'RES_EVENT_STREAM_ROW')
CREATE TABLE [dbo].[RES_EVENT_STREAM_ROW] (
	[RES_ESR_EventStreamRowId] [UNIQUEIDENTIFIER] NOT NULL,
	[RES_ESR_GlobalSequenceNumber] [BIGINT] IDENTITY(1,1) NOT NULL,
	[RES_ESR_StreamId] [UNIQUEIDENTIFIER] NOT NULL,
	[RES_ESR_StreamSequenceNumber] [BIGINT] NOT NULL,
	[RES_ESR_StoreDate] [DATETIMEOFFSET] NOT NULL,
	[RES_ESR_EventName] [VARCHAR] (50) NOT NULL,
	[RES_ESR_EventVersion] [INT] NOT NULL,
	[RES_ESR_EventJson] [NVARCHAR] (MAX) NOT NULL,
	[RES_ESR_AdditionalMetadataJson] [NVARCHAR] (MAX),
	[RES_ESR_IsDispatchedToAsyncQueues] [BIT] NOT NULL
	CONSTRAINT [RES_EVENT_STREAM_ROW_PK] PRIMARY KEY NONCLUSTERED ([RES_ESR_EventStreamRowId]),
	CONSTRAINT [RES_EVENT_STREAM_ROW_FK_EVENT_STREAM] FOREIGN KEY ([RES_ESR_StreamId]) REFERENCES [dbo].[RES_EVENT_STREAM] ([RES_EVS_EventStreamId]),
	CONSTRAINT [RES_EVENT_STREAM_ROW_UK_EVENT_STREAM_ID_AND_STREAM_SEQUENCE_NUMBER] UNIQUE([RES_ESR_StreamId], [RES_ESR_StreamSequenceNumber])
);
GO

/******
ASYNC EVENTS
******/

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'RAE_ASYNC_EVENT_QUEUE')
CREATE TABLE [dbo].[RAE_ASYNC_EVENT_QUEUE] (
	[RAE_AEQ_AsyncEventQueueId] [VARCHAR] (128) NOT NULL,
	[RAE_AEQ_Ordinal] [INT] IDENTITY(1,1) NOT NULL,
	[RAE_AEQ_Version] [INT] NOT NULL,
	[RAE_AEQ_LastSequenceNumberProcessed] [BIGINT],
	CONSTRAINT [RAE_ASYNC_EVENT_QUEUE_PK] PRIMARY KEY NONCLUSTERED ([RAE_AEQ_AsyncEventQueueId])
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'RAE_EXTERNAL_EVENT_RECORD')
CREATE TABLE [dbo].[RAE_EXTERNAL_EVENT_RECORD] (
	[RAE_EER_ExternalEventRecordId] [UNIQUEIDENTIFIER] NOT NULL,
	[RAE_EER_Ordinal] [INT] IDENTITY(1,1) NOT NULL,
	[RAE_EER_EventName] [VARCHAR] (50) NOT NULL,
	[RAE_EER_EventVersion] [INT] NOT NULL,
	[RAE_EER_EventJson] [NVARCHAR] (MAX) NOT NULL,
	[RAE_EER_MetadataJson] [NVARCHAR] (MAX)
	CONSTRAINT [RAE_EXTERNAL_EVENT_RECORD_PK] PRIMARY KEY NONCLUSTERED ([RAE_EER_ExternalEventRecordId])
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'RAE_QUEUED_ASYNC_EVENT')
CREATE TABLE [dbo].[RAE_QUEUED_ASYNC_EVENT] (
	[RAE_QAE_QueuedAsyncEventId] [UNIQUEIDENTIFIER] NOT NULL,
	[RAE_QAE_Ordinal] [INT] IDENTITY(1,1) NOT NULL,
	[RAE_QAE_QueueId] [VARCHAR] (128) NOT NULL,
	[RAE_QAE_SequenceNumber] [BIGINT],
	[RAE_QAE_EventStreamRowId] [UNIQUEIDENTIFIER],
	[RAE_QAE_ExternalEventRecordId] [UNIQUEIDENTIFIER],
	CONSTRAINT [RAE_QUEUED_ASYNC_EVENT_PK] PRIMARY KEY NONCLUSTERED ([RAE_QAE_QueuedAsyncEventId]),
	CONSTRAINT [RAE_QUEUE_ID_FK_ASYNC_EVENT_QUEUE] FOREIGN KEY ([RAE_QAE_QueueId]) REFERENCES [dbo].[RAE_ASYNC_EVENT_QUEUE] ([RAE_AEQ_AsyncEventQueueId]),
	CONSTRAINT [RAE_EVENT_STREAM_ROW_ID_FK_EVENT_STREAM_ROW] FOREIGN KEY ([RAE_QAE_EventStreamRowId]) REFERENCES [dbo].[RES_EVENT_STREAM_ROW] ([RES_ESR_EventStreamRowId]),
	CONSTRAINT [RAE_EXTERNAL_EVENT_RECORD_ID_FK_EXTERNAL_EVENT_RECORD] FOREIGN KEY ([RAE_QAE_ExternalEventRecordId]) REFERENCES [dbo].[RAE_EXTERNAL_EVENT_RECORD] ([RAE_EER_ExternalEventRecordId])
);
GO

/******
SAGAS
******/

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'REV_SAGA_METADATA_RECORD')
CREATE TABLE [dbo].[REV_SAGA_METADATA_RECORD] (
	[REV_SMR_SagaMetadataRecordId] [UNIQUEIDENTIFIER] NOT NULL,
	[REV_SMR_Ordinal] [INT] IDENTITY(1,1) NOT NULL,
	[REV_SMR_ClassId] [UNIQUEIDENTIFIER] NOT NULL
	CONSTRAINT [REV_SAGA_METADATA_RECORD_PK] PRIMARY KEY NONCLUSTERED ([REV_SMR_SagaMetadataRecordId])
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'REV_SAGA_METADATA_KEY')
CREATE TABLE [dbo].[REV_SAGA_METADATA_KEY] (
	[REV_SMK_SagaMetadataKeyId] [UNIQUEIDENTIFIER] NOT NULL,
	[REV_SMK_Ordinal] [INT] IDENTITY(1,1) NOT NULL,
	[REV_SMK_SagaId] [UNIQUEIDENTIFIER] NOT NULL,
	[REV_SMK_KeyName] [VARCHAR] (128) NOT NULL,
	[REV_SMK_KeyValue] [NVARCHAR] (MAX) NOT NULL
	CONSTRAINT [REV_SAGA_METADATA_KEY_PK] PRIMARY KEY NONCLUSTERED ([REV_SMK_SagaMetadataKeyId]),
	CONSTRAINT [REV_SAGA_METADATA_KEY_FK_SAGA_ID] FOREIGN KEY ([REV_SMK_SagaId]) REFERENCES [dbo].[REV_SAGA_METADATA_RECORD] ([REV_SMR_SagaMetadataRecordId])
);
GO

/******
HISTORY
******/

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'REV_TRACKED_CHANGE_RECORD')
CREATE TABLE [dbo].[REV_TRACKED_CHANGE_RECORD] (
	[REV_TCH_TrackedChangeRecordId] [UNIQUEIDENTIFIER] NOT NULL,
	[REV_TCH_Ordinal] [INT] IDENTITY(1,1) NOT NULL,
	[REV_TCH_ActorName] [NVARCHAR] (MAX) NOT NULL,
	[REV_TCH_UserId] [UNIQUEIDENTIFIER],
	[REV_TCH_AggregateId] [UNIQUEIDENTIFIER],
	[REV_TCH_AggregateClassId] [UNIQUEIDENTIFIER],
	[REV_TCH_EntityId] [UNIQUEIDENTIFIER],
	[REV_TCH_EntityClassId] [UNIQUEIDENTIFIER],
	[REV_TCH_ChangeTime] [DATETIMEOFFSET] NOT NULL,
	[REV_TCH_ChangeDataJson] [NVARCHAR] (MAX) NOT NULL,
	[REV_TCH_ChangeDataClassName] [NVARCHAR] (MAX) NOT NULL,
	CONSTRAINT [REV_TRACKED_CHANGE_RECORD_PK] PRIMARY KEY NONCLUSTERED ([REV_TCH_TrackedChangeRecordId])/*,
	CONSTRAINT [REV_TRACKED_CHANGE_RECORD_FK_USERID] FOREIGN KEY ([REV_TCH_UserId]) REFERENCES [dbo].[GT_USER] ([GT_USR_UserId])*/
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'REV_ENTITY_ATTRIBUTE_DATA')
CREATE TABLE [dbo].[REV_ENTITY_ATTRIBUTE_DATA] (
	[REV_EAD_EntityAttributeDataId] [UNIQUEIDENTIFIER] NOT NULL,
	[REV_EAD_Ordinal] [INT] IDENTITY(1,1) NOT NULL,
	[REV_EAD_AggregateId] [UNIQUEIDENTIFIER],
	[REV_EAD_EntityId] [UNIQUEIDENTIFIER],
	[REV_EAD_AttributeValueMapJson] [NVARCHAR] (MAX) NOT NULL,
	[REV_EAD_Version] [INT] NOT NULL,
	CONSTRAINT [REV_ENTITY_ATTRIBUTE_DATA_PK] PRIMARY KEY NONCLUSTERED ([REV_EAD_EntityAttributeDataId])
);
GO

/******
NOTIFICATIONS
******/

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'REV_NOTIFICATION_BUFFER')
CREATE TABLE [dbo].[REV_NOTIFICATION_BUFFER] (
	[REV_NBF_NotificationBufferId] [UNIQUEIDENTIFIER] NOT NULL,
	[REV_NBF_Ordinal] [INT] IDENTITY(1,1) NOT NULL,
	[REV_NBF_PipelineId] [UNIQUEIDENTIFIER] NOT NULL,
	[REV_NBF_GovernorId] [UNIQUEIDENTIFIER] NOT NULL
	CONSTRAINT [REV_NOTIFICATION_BUFFER_PK] PRIMARY KEY NONCLUSTERED ([REV_NBF_NotificationBufferId])
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'REV_BUFFERED_NOTIFICATION')
CREATE TABLE [dbo].[REV_BUFFERED_NOTIFICATION] (
	[REV_BNT_BufferedNotificationId] [UNIQUEIDENTIFIER] NOT NULL,
	[REV_BNT_Ordinal] [INT] IDENTITY(1,1) NOT NULL,
	[REV_BNT_NotificationClassName] [NVARCHAR] (MAX) NOT NULL,
	[REV_BNT_NotificationJson] [NVARCHAR] (MAX) NOT NULL,
	[REV_BNT_BufferId] [UNIQUEIDENTIFIER] NOT NULL,
	[REV_BNT_TimeQueued] [DATETIMEOFFSET] NOT NULL
	CONSTRAINT [REV_BUFFERED_NOTIFICATION_PK] PRIMARY KEY NONCLUSTERED ([REV_BNT_BufferedNotificationId]),
	CONSTRAINT [REV_BUFFERED_NOTIFICATION_FK_BUFFERID] FOREIGN KEY ([REV_BNT_BufferId]) REFERENCES [dbo].[REV_NOTIFICATION_BUFFER] ([REV_NBF_NotificationBufferId])
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'REV_APNS_USER_DEVICE_TOKEN')
CREATE TABLE [dbo].[REV_APNS_USER_DEVICE_TOKEN] (
	[REV_AUT_ApnsUserDeviceTokenId] [UNIQUEIDENTIFIER] NOT NULL,
	[REV_AUT_Ordinal] [INT] IDENTITY(1,1) NOT NULL,
	[REV_AUT_Version] [INT] NOT NULL,
	[REV_AUT_UserId] [UNIQUEIDENTIFIER] NOT NULL,
	[REV_AUT_DeviceToken] [NVARCHAR] (MAX) NOT NULL,
	[REV_AUT_AppId] [VARCHAR] (255) NOT NULL,
	[REV_AUT_IssuedDateTime] [DATETIMEOFFSET] NOT NULL
	CONSTRAINT [REV_APNS_USER_DEVICE_TOKEN_PK] PRIMARY KEY NONCLUSTERED ([REV_AUT_ApnsUserDeviceTokenId])/*,
	CONSTRAINT [REV_APNS_USER_DEVICE_TOKEN_FK_USERID] FOREIGN KEY ([REV_AUT_UserId]) REFERENCES [dbo].[GT_USER] ([GT_USR_UserId])*/
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'REV_APNS_EXTERNAL_USER_DEVICE_TOKEN')
CREATE TABLE [dbo].[REV_APNS_EXTERNAL_USER_DEVICE_TOKEN] (
	[REV_AET_ApnsExternalUserDeviceTokenId] [UNIQUEIDENTIFIER] NOT NULL,
	[REV_AET_Ordinal] [INT] IDENTITY(1,1) NOT NULL,
	[REV_AET_Version] [INT] NOT NULL,
	[REV_AET_ExternalUserId] [UNIQUEIDENTIFIER] NOT NULL,
	[REV_AET_DeviceToken] [NVARCHAR] (MAX) NOT NULL,
	[REV_AET_AppId] [VARCHAR] (255) NOT NULL,
	[REV_AET_IssuedDateTime] [DATETIMEOFFSET] NOT NULL
	CONSTRAINT [REV_APNS_EXTERNAL_USER_DEVICE_TOKEN_PK] PRIMARY KEY NONCLUSTERED ([REV_AET_ApnsExternalUserDeviceTokenId])
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'REV_FCM_USER_DEVICE_TOKEN')
CREATE TABLE [dbo].[REV_FCM_USER_DEVICE_TOKEN] (
	[REV_FUT_FcmUserDeviceTokenId] [UNIQUEIDENTIFIER] NOT NULL,
	[REV_FUT_Ordinal] [INT] IDENTITY(1,1) NOT NULL,
	[REV_FUT_Version] [INT] NOT NULL,
	[REV_FUT_UserId] [UNIQUEIDENTIFIER] NOT NULL,
	[REV_FUT_RegistrationId] [NVARCHAR] (MAX) NOT NULL,
	[REV_FUT_AppId] [VARCHAR] (255) NOT NULL,
	[REV_FUT_IssuedDateTime] [DATETIMEOFFSET] NOT NULL
	CONSTRAINT [REV_FCM_USER_DEVICE_TOKEN_PK] PRIMARY KEY NONCLUSTERED ([REV_FUT_FcmUserDeviceTokenId])/*,
	CONSTRAINT [REV_FCM_USER_DEVICE_TOKEN_FK_USERID] FOREIGN KEY ([REV_FUT_UserId]) REFERENCES [dbo].[GT_USER] ([GT_USR_UserId])*/
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'REV_FCM_EXTERNAL_USER_DEVICE_TOKEN')
CREATE TABLE [dbo].[REV_FCM_EXTERNAL_USER_DEVICE_TOKEN] (
	[REV_FET_FcmExternalUserDeviceTokenId] [UNIQUEIDENTIFIER] NOT NULL,
	[REV_FET_Ordinal] [INT] IDENTITY(1,1) NOT NULL,
	[REV_FET_Version] [INT] NOT NULL,
	[REV_FET_ExternalUserId] [UNIQUEIDENTIFIER] NOT NULL,
	[REV_FET_RegistrationId] [NVARCHAR] (MAX) NOT NULL,
	[REV_FET_AppId] [VARCHAR] (255) NOT NULL,
	[REV_FET_IssuedDateTime] [DATETIMEOFFSET] NOT NULL
	CONSTRAINT [REV_FCM_EXTERNAL_USER_DEVICE_TOKEN_PK] PRIMARY KEY NONCLUSTERED ([REV_FET_FcmExternalUserDeviceTokenId])
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'REV_LOCALIZATION_MESSAGE')
CREATE TABLE [dbo].[REV_LOCALIZATION_MESSAGE] (
	[REV_LOM_LocalizationMessageId] [UNIQUEIDENTIFIER],
	[REV_LOM_Ordinal] [INT] IDENTITY(1,1),
	[REV_LOM_Version] [INT] NOT NULL,
	[REV_LOM_TenantId] [UNIQUEIDENTIFIER],
	[REV_LOM_ClassName] [VARCHAR](1024) NOT NULL,
	[REV_LOM_Key] [NVARCHAR](255) NOT NULL,
	[REV_LOM_Message] [NVARCHAR](MAX),
	[REV_LOM_LocaleCode] [VARCHAR](128) NOT NULL,
	CONSTRAINT [REV_LOCALIZATION_MESSAGE_PK] PRIMARY KEY NONCLUSTERED ([REV_LOM_LocalizationMessageId])
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'REV_SERVICE_TOKEN')
CREATE TABLE [dbo].[REV_SERVICE_TOKEN] (
	[REV_SRT_ServiceTokenId] [UNIQUEIDENTIFIER],
	[REV_SRT_Ordinal] [INT] IDENTITY(1,1),
	[REV_SRT_Version] [INT],
	[REV_SRT_ServiceName] [NVARCHAR](512) NOT NULL,
	[REV_SRT_Timestamp] [DATETIMEOFFSET] DEFAULT GETDATE()
	CONSTRAINT [REV_SERVICE_TOKEN_PK] PRIMARY KEY NONCLUSTERED ([REV_SRT_ServiceTokenId])
);
GO


/**********
Database versioning infrastructure
**********/

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'REV_INSTANCE')
CREATE TABLE [REV_INSTANCE] (
	[REV_INS_InstanceId] [UNIQUEIDENTIFIER],
	[REV_INS_Ordinal] [INT] IDENTITY(1,1),
	[REV_INS_Version] [INT] NOT NULL,
	[REV_INS_Name] [NVARCHAR](1024) NOT NULL,
	[REV_INS_InstanceVersion] [NVARCHAR](4000),
	CONSTRAINT [REV_INSTANCE_PK] PRIMARY KEY NONCLUSTERED ([REV_INS_InstanceId])
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'REV_MODULE')
CREATE TABLE [REV_MODULE] (
	[REV_MOD_ModuleId] [UNIQUEIDENTIFIER],
	[REV_MOD_Ordinal] [INT] IDENTITY(1,1),
	[REV_MOD_Version] [INT] NOT NULL,
	[REV_MOD_Name] [NVARCHAR](1024) NOT NULL,		
	CONSTRAINT [REV_MODULE_PK] PRIMARY KEY NONCLUSTERED ([REV_MOD_ModuleId])	
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'REV_MODULE_INSTANCE')
CREATE TABLE [REV_MODULE_INSTANCE] (
	[REV_MOI_ModuleInstanceId] [UNIQUEIDENTIFIER],
	[REV_MOI_Ordinal] [INT] IDENTITY(1,1),
	[REV_MOI_Version] [INT] NOT NULL,
	[REV_MOI_InstanceVersion] [VARCHAR](4000) NOT NULL,
	[REV_MOI_ModuleId] [UNIQUEIDENTIFIER] NOT NULL,
	[REV_MOI_InstanceId] [UNIQUEIDENTIFIER] NOT NULL,
	CONSTRAINT [REV_MODULE_INSTANCE_PK] PRIMARY KEY NONCLUSTERED ([REV_MOI_ModuleInstanceId]),
	CONSTRAINT [REV_MODULE_INSTANCE_FK_SERVER_INSTANCE] FOREIGN KEY ([REV_MOI_InstanceId]) REFERENCES [dbo].[REV_INSTANCE]([REV_INS_InstanceId]) ON DELETE CASCADE,
	CONSTRAINT [REV_MODULE_INSTANCE_FK_MODULE] FOREIGN KEY ([REV_MOI_ModuleId]) REFERENCES [dbo].[REV_MODULE]([REV_MOD_ModuleId]) ON DELETE CASCADE
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'REV_LIBRARY')
CREATE TABLE [REV_LIBRARY] (
	[REV_LIB_LibraryId] [UNIQUEIDENTIFIER],
	[REV_LIB_Ordinal] [INT] IDENTITY(1,1),
	[REV_LIB_Version] [INT] NOT NULL,
	[REV_LIB_AssemblyName] [NVARCHAR](4000) NOT NULL,
	[REV_LIB_AssemblyVersion] [VARCHAR](4000) NOT NULL,
	[REV_LIB_ModuleInstanceId] [UNIQUEIDENTIFIER] NOT NULL,
	CONSTRAINT [REV_LIBRARY_PK] PRIMARY KEY NONCLUSTERED ([REV_LIB_LibraryId]),
	CONSTRAINT [REV_LIBRARY_FK_MODULE] FOREIGN KEY ([REV_LIB_ModuleInstanceId]) REFERENCES [dbo].[REV_MODULE_INSTANCE]([REV_MOI_ModuleInstanceId]) ON DELETE CASCADE
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'REV_DB_VERSION')
CREATE TABLE [REV_DB_VERSION] (
	[REV_DBV_DbVersionId] [UNIQUEIDENTIFIER],
	[REV_DBV_Ordinal] [INT] IDENTITY(1,1),
	[REV_DBV_ModuleId] [UNIQUEIDENTIFIER] NOT NULL,
	[REV_DBV_Version] [VARCHAR](255) NOT NULL,
	[REV_DBV_MinModuleVersion] [VARCHAR](255) NOT NULL,
	[REV_DBV_MaxModuleVersion] [VARCHAR](255) NOT NULL,	
	CONSTRAINT [REV_DB_VERSION_PK] PRIMARY KEY NONCLUSTERED ([REV_DBV_DbVersionId]),
	CONSTRAINT [REV_DB_VERSION_FK_MODULE] FOREIGN KEY ([REV_DBV_ModuleId]) REFERENCES [dbo].[REV_MODULE]([REV_MOD_ModuleId])
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'REV_DATA_VERSION')
CREATE TABLE [REV_DATA_VERSION] (
	[REV_DTV_DataVersionId] [UNIQUEIDENTIFIER],
	[REV_DTV_Ordinal] [INT] IDENTITY(1,1),
	[REV_DTV_Serie] [NVARCHAR](1024),
	[REV_DTV_Version] [VARCHAR](255) NOT NULL,
	CONSTRAINT [REV_DATA_VERSION_PK] PRIMARY KEY NONCLUSTERED ([REV_DTV_DataVersionId])
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'REV_SCRIPT_LOG')
CREATE TABLE [REV_SCRIPT_LOG] (
	[REV_SCL_ScriptLogId] [UNIQUEIDENTIFIER],
	[REV_SCL_Ordinal] [INT] IDENTITY(1,1),
	[REV_SCL_ScriptId] [UNIQUEIDENTIFIER] NOT NULL,
	[REV_SCL_ScriptVersion] [VARCHAR](255),
	[REV_SCL_ScriptType] [VARCHAR](255) NOT NULL,
	[REV_SCL_ScriptName] [NVARCHAR](1024) NOT NULL,
	[REV_SCL_DbVersionId] [UNIQUEIDENTIFIER],
	[REV_SCL_DataVersionId] [UNIQUEIDENTIFIER],
	[REV_SCL_StartTimestamp] [DATETIME] NOT NULL,
	[REV_SCL_CompletionTimestamp] [DATETIME],
	CONSTRAINT [REV_SCRIPT_LOG_PK] PRIMARY KEY NONCLUSTERED ([REV_SCL_ScriptLogId]),
	CONSTRAINT [REV_SCRIPT_LOG_FK_DB_VERSION] FOREIGN KEY ([REV_SCL_DbVersionId]) REFERENCES [dbo].[REV_DB_VERSION]([REV_DBV_DbVersionId]),
	CONSTRAINT [REV_SCRIPT_LOG_FK_DATA_VERSION] FOREIGN KEY ([REV_SCL_DataVersionId]) REFERENCES [dbo].[REV_DATA_VERSION]([REV_DTV_DataVersionId])
);
GO

/*******************************************************************/
--a bit more complex because of possible bootstrap phase
IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'REV_TEMP_SCRIPT_LOG')
BEGIN

	INSERT INTO REV_MODULE (REV_MOD_ModuleId, REV_MOD_Version, REV_MOD_Name)
	VALUES ('5F08DF74-3C4B-4DBD-AD35-26565239E157',1,'Revo.Infrastructure')

	INSERT INTO [REV_DB_VERSION] (REV_DBV_DbVersionId, REV_DBV_ModuleId, REV_DBV_Version, REV_DBV_MinModuleVersion, REV_DBV_MaxModuleVersion)
	SELECT REV_DBV_DbVersionId, REV_DBV_ModuleId, REV_DBV_Version, REV_DBV_MinModuleVersion, REV_DBV_MaxModuleVersion
	FROM	[REV_TEMP_DB_VERSION];
	
	INSERT INTO [dbo].[REV_SCRIPT_LOG] ([REV_SCL_ScriptLogId],[REV_SCL_ScriptId], [REV_SCL_ScriptVersion], [REV_SCL_ScriptType],[REV_SCL_ScriptName],[REV_SCL_DbVersionId],[REV_SCL_StartTimestamp],[REV_SCL_CompletionTimestamp])
	SELECT	[REV_SCL_ScriptLogId],[REV_SCL_ScriptId],[REV_SCL_ScriptVersion], [REV_SCL_ScriptType],[REV_SCL_ScriptName],[REV_SCL_DbVersionId],[REV_SCL_StartTimestamp],[REV_SCL_CompletionTimestamp]
	FROM	[REV_TEMP_SCRIPT_LOG];
	DROP TABLE [REV_TEMP_SCRIPT_LOG];
	DROP TABLE [REV_TEMP_DB_VERSION];

	UPDATE [dbo].[REV_SCRIPT_LOG]
	SET	[REV_SCL_CompletionTimestamp] = GETDATE()
	WHERE	[REV_SCL_ScriptLogId] = (
	SELECT	TOP 1 [REV_SCL_ScriptLogId]
	FROM	[dbo].[REV_SCRIPT_LOG]
	WHERE	[REV_SCL_ScriptId] = '1FBA6358-7AC1-4B6F-82D6-48BBCBD5C99E' AND [REV_SCL_CompletionTimestamp] IS NULL
	ORDER BY [REV_SCL_StartTimestamp] DESC)


END
ELSE
	UPDATE [dbo].[REV_SCRIPT_LOG]
	SET	[REV_SCL_CompletionTimestamp] = GETDATE()
	WHERE [REV_SCL_ScriptId]='1FBA6358-7AC1-4B6F-82D6-48BBCBD5C99E'
			AND
			[REV_SCL_CompletionTimestamp] IS NULL;

