/*
ModuleId: 5F08DF74-3C4B-4DBD-AD35-26565239E157
Version: 1.0.0
ScriptId: 77839C5A-48FC-42CF-B952-EF65AD7E84FD
*/
IF NOT EXISTS (SELECT 1 FROM [dbo].[REV_SCRIPT_LOG] WHERE [REV_SCL_ScriptId] = '1FBA6358-7AC1-4B6F-82D6-48BBCBD5C99E' AND [REV_SCL_CompletionTimestamp] IS NOT NULL)
	RAISERROR('Revo create script must be run first.', 20, 1)  WITH LOG;
GO
EXEC [dbo].[REV_SP_CheckScriptsRun] 'CDED157F-2538-4F33-81E0-4B2DD1BCC4AA';
GO
EXEC [dbo].[REV_SP_RunStructureScript] '77839C5A-48FC-42CF-B952-EF65AD7E84FD', '03_REV_INDICES.sql', 'DCB948CF-C9DB-41C9-AE9C-C08E97BC87B2', '1.0.0';
GO
/******
EVENT STORE
******/

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'CIX_RES_EVENT_STREAM')
	CREATE CLUSTERED INDEX [CIX_RES_EVENT_STREAM] ON [dbo].[RES_EVENT_STREAM] ([RES_EVS_Ordinal]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'CIX_RES_EVENT_STREAM_ROW')
	CREATE UNIQUE CLUSTERED INDEX [CIX_RES_EVENT_STREAM_ROW] ON [dbo].[RES_EVENT_STREAM_ROW] ([RES_ESR_GlobalSequenceNumber]);
GO

/******
ASYNC EVENTS
******/

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'CIX_RAE_ASYNC_EVENT_QUEUE')
	CREATE UNIQUE CLUSTERED INDEX [CIX_RAE_ASYNC_EVENT_QUEUE] ON [dbo].[RAE_ASYNC_EVENT_QUEUE] ([RAE_AEQ_Ordinal]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'CIX_RAE_EXTERNAL_EVENT_RECORD')
	CREATE UNIQUE CLUSTERED INDEX [CIX_RAE_EXTERNAL_EVENT_RECORD] ON [dbo].[RAE_EXTERNAL_EVENT_RECORD] ([RAE_EER_Ordinal]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'CIX_RAE_QUEUED_ASYNC_EVENT')
	CREATE UNIQUE CLUSTERED INDEX [CIX_RAE_QUEUED_ASYNC_EVENT] ON [dbo].[RAE_QUEUED_ASYNC_EVENT] ([RAE_QAE_Ordinal]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UIX_RAE_QUEUED_ASYNC_EVENT')
	CREATE UNIQUE NONCLUSTERED INDEX [UIX_RAE_QUEUED_ASYNC_EVENT] ON [dbo].[RAE_QUEUED_ASYNC_EVENT] ([RAE_QAE_QueueId], [RAE_QAE_SequenceNumber]) WHERE [RAE_QAE_SequenceNumber] IS NOT NULL;
GO

/*** TODO ***/

/************************************************/
EXEC [dbo].[REV_SP_CompleteStructureScript] '77839C5A-48FC-42CF-B952-EF65AD7E84FD', '1.0.0';