/*
ModuleId: 5F08DF74-3C4B-4DBD-AD35-26565239E157
Version: 1.0.0
ScriptId: 5981AF9B-5BC3-44BD-A7D7-572FB328AABA
*/

IF EXISTS (SELECT 1 FROM sys.tables WHERE name IN ('REV_TEMP_DB_VERSION','REV_DB_VERSION'))	
		RAISERROR('This script can be run only once!', 20, 1)  WITH LOG;

CREATE TABLE [dbo].[REV_TEMP_DB_VERSION] (
[REV_DBV_DbVersionId] [UNIQUEIDENTIFIER],
[REV_DBV_ModuleId] [UNIQUEIDENTIFIER] NOT NULL,
[REV_DBV_Version] [VARCHAR](255) NOT NULL,
[REV_DBV_MinModuleVersion] [VARCHAR](255) NOT NULL,
[REV_DBV_MaxModuleVersion] [VARCHAR](255) NOT NULL
);
GO

CREATE TABLE [REV_TEMP_SCRIPT_LOG] (
	[REV_SCL_ScriptLogId] [UNIQUEIDENTIFIER],	
	[REV_SCL_ScriptId] [UNIQUEIDENTIFIER] NOT NULL,
	[REV_SCL_ScriptVersion] [VARCHAR](255),
	[REV_SCL_ScriptType] [VARCHAR](255) NOT NULL,
	[REV_SCL_ScriptName] [NVARCHAR](1024) NOT NULL,
	[REV_SCL_DbVersionId] [UNIQUEIDENTIFIER],
	[REV_SCL_DataVersionId] [UNIQUEIDENTIFIER],
	[REV_SCL_StartTimestamp] [DATETIME] NOT NULL,
	[REV_SCL_CompletionTimestamp] [DATETIME]
);
GO


INSERT INTO [REV_TEMP_DB_VERSION] (REV_DBV_DbVersionId, REV_DBV_ModuleId, REV_DBV_Version, REV_DBV_MinModuleVersion, REV_DBV_MaxModuleVersion)
VALUES ('DCB948CF-C9DB-41C9-AE9C-C08E97BC87B2', '5F08DF74-3C4B-4DBD-AD35-26565239E157', 'INSTALLING-1.0.0', '1.0.0', '1.0.0');
GO

DECLARE @logId UNIQUEIDENTIFIER = NEWID();
DECLARE @timestamp DATETIME = GETDATE();
INSERT INTO [dbo].[REV_TEMP_SCRIPT_LOG] ([REV_SCL_ScriptLogId],[REV_SCL_ScriptId], [REV_SCL_ScriptVersion],[REV_SCL_ScriptType],[REV_SCL_ScriptName],[REV_SCL_DbVersionId],[REV_SCL_StartTimestamp],[REV_SCL_CompletionTimestamp])
VALUES (@logId, '5981AF9B-5BC3-44BD-A7D7-572FB328AABA', '1.0.0', 'STRUCTURE', '01_Revo_Infrastructure_init_start', 'DCB948CF-C9DB-41C9-AE9C-C08E97BC87B2', @timestamp, @timestamp);
